# Generated by Django 4.2.3 on 2023-07-16 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[(0, 'Nowy'), (1, 'W toku'), (2, 'Rozwiązany')], default='Nowy', max_length=100)),
                ('users', models.ManyToManyField(blank=True, help_text='The users this task belongs to.', related_name='user_set', related_query_name='user', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
    ]
