# Generated by Django 3.2.12 on 2023-07-17 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[(0, 'Nowy'), (1, 'W toku'), (2, 'Rozwiązany')], default='Nowy', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[(0, 'Creation'), (1, 'Edit'), (2, 'Removal')], max_length=100)),
                ('users', models.ManyToManyField(blank=True, help_text='The users this task belongs to.', related_name='history_set', related_query_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
