# Generated by Django 3.2.12 on 2023-07-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.IntegerField(choices=[(0, 'Creation'), (1, 'Edit'), (2, 'Removal')]),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.IntegerField(choices=[(0, 'Nowy'), (1, 'W toku'), (2, 'Rozwiązany')], default=0),
        ),
    ]
